version: '3.8'

services:
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile.minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./minio/minio.env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data: