version: '3.8'

services:
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile.minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./minio/minio.env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"


  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./mongodb/mongodb.env
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/backend.env
    depends_on:
      - mongodb
      - minio

      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/frontend.env
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  minio-data:
  mongo-data: