# Use the official MinIO image from the Docker Hub
FROM minio/minio:latest

# Set the working directory
WORKDIR /data

# Expose the ports for MinIO (default is 9000 and 9001)
EXPOSE 9000
EXPOSE 9001

# Set the command to run MinIO server
CMD ["minio", "server", "/data"]